### ISSUE TITLE
GENERIC oils

### ISSUE THREAD

**Issue by gauteh** [NOAA-ORR-ERD/adios_oil_database#5]
Hi,

in the previous oil database there were a bunch of generic oils, I have been trying to link those to existing ones by looking at the adios code. But I cannot find likely candidates for these. Have these been removed or have they been renamed?

Specifically these are important to us (some of the specific ones have been added by us to our version @knutfrode):

```
 'GENERIC BUNKER C',        'GENERIC DIESEL',        'GENERIC LIGHT CRUDE' , 
'GENERIC HEAVY CRUDE', 'GENERIC JET FUEL', 'OSEBERG SOR 2000', 
'KVITEBJORN 2019', 'VISUND CRUDE OIL 2020', 'IRIS CONDENSATE 2020',
 'FOGELBERG CONDENSATE 2021', 'VISUND SOR CONDENSATE 2020', 
'GENERIC HOME HEATING OIL', 'VEGA CONDENSATE 2015', 'AASTA HANSTEEN BLEND 2020', 
'GENERIC INTERMEDIATE FUEL OIL 300', 'GINA KROG CRUDE (2018)', 'GENERIC MEDIUM CRUDE',
 'SKOGUL 2020', 'GENERIC GASOLINE', 'DVALIN 2020', 'ATLA KONDENSAT 2013', 'ODA 2019',
 'GUDRUN 2019', 'GENERIC INTERMEDIATE FUEL OIL 180', 'GENERIC FUEL OIL No. 6',
 'GENERIC HEAVY FUEL OIL', 'FROSK 2020', 'GENERIC FUEL OIL No.2', 'FENJA (PIL) 2015', 
'MARULK (2014)', 'OSEBERG OST 1998'
```

**Comment by ChrisBarker-NOAA** [comment]
Sorry, this is a real limitation.

We too want "generic" oils.

The trick is that we kind of jumped the gun when we put them in the old OilLibrary -- we needed something, so we put in placeholders ( I think they all are simply another oil renamed) with intention of going back and "doing it right", and making sure that they really are representative oils.

That's still on our ToDo list, but I'm not sure when it might happen.

We do welcome collaboration, if you want to help us develop a proper set.

In the meantime, we should be able to make new-style records from the previous generic set, but I'd be wary of distributing them at this point without more review.

**Comment by gauteh** [comment]
Ok, thanks. It is probably not very important to us that they are exactly the same as before, as long as they are reasonable choice. They can be aliases. I will try to come up with a list, and we can see if that is useful for you as well. If there is any information about which oils they were linked to previously, that would be very useful. It is not very important to us that they are re-introduced into ADIOS, we have to keep a small list of aliases anyway.

We have some new oils, and updates to names, in the old format. How should we submit these for inclusion in the new DB?

**Comment by gauteh** [comment]
We are using the oils from OilLibTest to generate the old GENERIC oil. Closing this, as you probably do not want them in your new db.

**Comment by ChrisBarker-NOAA** [comment]
That sounds like a fine plan.

FYI: we are going to create a new set more systematically within the next year or so.

BTW: you wrote:
"We have some new oils, and updates to names, in the old format. How should we submit these for inclusion in the new DB?"

Are you still interested in doing that? Easiest for us would be to put them in the new JSON format yourself -- the new code makes that not too difficult. You could even use the Web Interface -- there is an editable version as well.

Alternatively, we can work together on a spreadsheet format that can easily be imported.

**Comment by gauteh** [comment]
Hi Chris,

I just today converted them to json using the new code:
https://github.com/OpenDrift/opendrift/tree/master/opendrift/models/openoil/adios/extra_oils

does that work?

Regards, Gaute

man. 3. jan. 2022, 19:47 skrev Chris Barker ***@***.***>:

**Comment by ChrisBarker-NOAA** [comment]
That looks great -- I'll comment over on that repo.
